### ISSUE TITLE
About visualization

### ISSUE THREAD

**Issue by xlbjy** [Toytiny/CMFlow#5]
Hi, nice work! I would like to ask a few questions about visualization. 
1）How to display the radar points projected from the source frame to the corresponding RGB image as shown in Figure 4 (the points are colored based on the distance from the distance sensor)?
2）How to achieve visualization of point clouds as shown in Figure 4 (from the second column to the fourth column)?
3）Why are the two point clouds in the ground truth image not strictly coincident?
4）How to visualize odometry results as shown in Figure 7?
Thank you!

**Comment by Toytiny** [comment]
Hi, thanks for your attention to our work!

1) you could use some functions in the vod library for visualization. You may need to refer to the answer to another issue: #2 
2) we use the open3d library to visualize the points and the warped one. You can save the results by modifying the save_res to True and write your own scripts for visualization. 
3) Because in real-world point clouds, particularly radar point clouds, unlike the simulated ones, there are no strict point-to-point correpondences between two frames (for more details, please see the point cloud generation principle of mmwave radar). That's why the points can not exactly match each other after warping. That's also one challenge for our work, i.e., how to estimate accurate scene flow on such point clouds.
4) you could save the inference results by modifying the save_res to True and aggregate the 'pred_t' from our samples in one sequence for odometry visualisation.

Thanks for your questions again! Hope these answers can help you with your research.

**Comment by gonglos** [comment]
Thank you for your reply. I just trained the CMFlow model, and the test results are slightly different from yours. I got a slightly worse results than yours.

{'exp_name': 'cmflow_ours', 'model': 'cmflow', 'num_points': 256, 'batch_size': 16, 'val_batch_size': 8, 'epochs': 60, 'lr': 0.001, 'decay_epochs': 1, 'decay_rate': 0.9, 'cuda_device': '0', 'no_cuda': False, 'seed': 1234, 'num_workers': 8, 'eval': True, 'eval_split': 'test', 'dataset': 'vodDataset', 'train_set': 'train', 'dataset_path': '/media/ps/Extreme SSD/flow_smp', 'vis': False, 'save_res': False, 'rigid_thres': 0.15, 'vr_thres': 0.3, 'stat_thres': 0.5, 'mini_clip_len': 5, 'update_len': 5, 'load_checkpoint': False, 'model_path': ''}
test : 2717
###The inference speed is 20.147ms per frame###
###The mean rne: 0.06271448002027093###
###The mean 50-50 rne: 0.06833748433770244###
###The mean mov_rne: 0.07590145133036093###
###The mean stat_rne: 0.06077351734504403###
###The mean sas: 0.8505988896579922###
###The mean ras: 0.969322748586407###
###The mean epe: 0.15613189407198919###
###The mean accs: 0.21141466534648493###
###The mean accr: 0.46134891088725427###
###The mean acc: 0.8412440868975742###
###The mean miou: 0.5365694685631337###
###The mean sen: 0.8631935093620346###
###The mean RTE: 0.0894211387632732###
###The mean RAE: 0.1791846508333119###

The parameter settings are same as your provided original configs.yaml.

exp_name: cmflow_cvpr
model: cmflow
## training 
num_points: 256
batch_size: 16 #16 32
val_batch_size: 8 #8 16
epochs: 60 #30
lr: 0.001 #0.001
decay_epochs: 1
decay_rate: 0.9

## device
cuda_device: '0'
no_cuda: False
seed: 1234
num_workers: 8

## dataset
eval: True
eval_split: test
dataset: vodDataset # vodClipDataset
train_set: train 
dataset_path: /mnt/12T/fangqiang/preprocess_res/flow_smp/
vis: False
save_res: False

## RaFlow method parameter
rigid_thres: 0.15

## CMFlow method parameter
vr_thres: 0.3 # 0.3 used for train
stat_thres: 0.5 # for test

## GRU parameter
mini_clip_len: 5
update_len: 5

## checkpoint
load_checkpoint: False
model_path: ''

May I ask if this result is normal?

**Comment by Toytiny** [comment]
Hi,

the configuration seems ok. A relative deviation lower than 10% is acceptable. Your AccR is 46.1%, which is only 3% lower than ours. The performance difference may be due to different hardware. We notice that your inference speed is faster than ours, which indicates that you use a new series of Nvidia GTX, possibly 4090 or higher. With different hardware, the generated pseudo optical flow labels through RAFT model might be different, and the main training is also affected.  Even with the same GPU, the performance is also likely to be different as we utilize 8 workers for data reading. The index of CPUs workers also has an influence on the performance. 

To improve the performance, we recommend you use a smaller training batch size, e.g. 8, and train our model again. To prove that you reproduction is correct, you can use our provided model for test and see if the results are the same as ours.

**Comment by gonglos** [comment]
OK. Thank you very much for your reply. Yes, we used new GPU 4090 for training. Thank you for your suggestion. We will try a smaller training batch for training.
